markdown: redcarpet
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Jarrod C Taylor
production_url : http://jarrodctaylor.com
description: "Vim, Python, Shell and all things open source"
disqus_shortname: jarrodctaylorcom
author :
  name : Jarrod C Taylor
  github : JarrodCTaylor
  twitter: JarrodCTaylor
  email: jarrod@JarrodCTaylor.com
