markdown: kramdown
highlighter: rouge
permalink: /posts/:title/
rdiscount:
  extensions: [smart]
title : Jarrod C Taylor
production_url : http://jarrodctaylor.com
description: "Clojure, Vim, Shell, Python and all things open source"
author :
  name : Jarrod C Taylor
  github : JarrodCTaylor
  twitter: JarrodCTaylor
  email: jarrod@JarrodCTaylor.com
