markdown: kramdown
highlighter: rouge
permalink: /posts/:title/
rdiscount:
  extensions: [smart]
title : Jarrod C Taylor
production_url : http://jarrodctaylor.com
description: "All things that might go beep and boop"
author :
  name : Jarrod C Taylor
  github : JarrodCTaylor
  twitter: JarrodCTaylor
  email: jarrod@JarrodCTaylor.com
